### ISSUE TITLE
a few suggestions for additional content on the website

### ISSUE THREAD

**Issue by oren** [convox/website#3]
I think it would be nice to have a page that describes the difference between this project and other similar projects - Deis, Mesos, Kubernetes etc. Goal, scope, target audience, required skill-set, scaling, performance etc.

Also nice to have is a page with a few diagrams that describe both the AWS infrastructure created by the 'install' command and whatever happens on the 'deploy' command.

**Comment by nzoschke** [comment]
Thanks for your feedback. We will track project comparisons and architecture diagrams internally.
